/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author sofic
 */
public class VistaSingIn extends javax.swing.JFrame {

    /**
     * Creates new form VistaSingIn
     */
    public VistaSingIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NombreCliente = new javax.swing.JTextField();
        ApellidoCliente = new javax.swing.JTextField();
        RTNcliente = new javax.swing.JTextField();
        CorreoCliente = new javax.swing.JTextField();
        TelefonoCliente = new javax.swing.JTextField();
        FechanaCliente = new javax.swing.JTextField();
        ButtomCrearCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ButtonChangeLogIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 122, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("REGISTRARSE");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(193, 58, 37));
        jLabel4.setText("RELLENE LOS SIGUIENTES DATOS:");

        NombreCliente.setBackground(new java.awt.Color(204, 204, 204));
        NombreCliente.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        NombreCliente.setForeground(new java.awt.Color(51, 51, 51));
        NombreCliente.setText("NOMBRE");
        NombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreClienteActionPerformed(evt);
            }
        });

        ApellidoCliente.setBackground(new java.awt.Color(204, 204, 204));
        ApellidoCliente.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        ApellidoCliente.setForeground(new java.awt.Color(51, 51, 51));
        ApellidoCliente.setText("APELLIDO");
        ApellidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoClienteActionPerformed(evt);
            }
        });

        RTNcliente.setBackground(new java.awt.Color(204, 204, 204));
        RTNcliente.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        RTNcliente.setForeground(new java.awt.Color(51, 51, 51));
        RTNcliente.setText("RTN");
        RTNcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RTNclienteActionPerformed(evt);
            }
        });

        CorreoCliente.setBackground(new java.awt.Color(204, 204, 204));
        CorreoCliente.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        CorreoCliente.setForeground(new java.awt.Color(51, 51, 51));
        CorreoCliente.setText("E-MAIL");
        CorreoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoClienteClienteActionPerformed(evt);
            }
        });

        TelefonoCliente.setBackground(new java.awt.Color(204, 204, 204));
        TelefonoCliente.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        TelefonoCliente.setForeground(new java.awt.Color(51, 51, 51));
        TelefonoCliente.setText("TELEFONO");
        TelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoClienteClienteActionPerformed(evt);
            }
        });

        FechanaCliente.setBackground(new java.awt.Color(204, 204, 204));
        FechanaCliente.setForeground(new java.awt.Color(51, 51, 51));
        FechanaCliente.setText("FECHA NACIMIENTO");

        ButtomCrearCuenta.setBackground(new java.awt.Color(233, 148, 30));
        ButtomCrearCuenta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtomCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        ButtomCrearCuenta.setText("CREAR CUENTA");
        ButtomCrearCuenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        ButtomCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtomCrearCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(TelefonoCliente)
                                .addComponent(CorreoCliente)
                                .addComponent(RTNcliente)
                                .addComponent(ApellidoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                                .addComponent(FechanaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(ButtomCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RTNcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FechanaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtomCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/QuesoMarketlogo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 480, 260));

        ButtonChangeLogIn.setBackground(new java.awt.Color(193, 58, 37));
        ButtonChangeLogIn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonChangeLogIn.setText("INICIAR SESIÓN");
        ButtonChangeLogIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(ButtonChangeLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 180, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/BgSingUp.png"))); // NOI18N
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 1000, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreClienteActionPerformed

    private void RTNclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RTNclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RTNclienteActionPerformed

    private void CorreoClienteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoClienteClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoClienteClienteActionPerformed

    private void TelefonoClienteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoClienteClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoClienteClienteActionPerformed

    private void ApellidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoClienteActionPerformed

    private void ButtomCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtomCrearCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtomCrearCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSingIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoCliente;
    private javax.swing.JButton ButtomCrearCuenta;
    private javax.swing.JButton ButtonChangeLogIn;
    private javax.swing.JTextField CorreoCliente;
    private javax.swing.JTextField FechanaCliente;
    private javax.swing.JTextField NombreCliente;
    private javax.swing.JTextField RTNcliente;
    private javax.swing.JTextField TelefonoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
